FROM python:latest
COPY requirements-stg.txt requirements-stg.txt
RUN python3 -m venv .venv
RUN . .venv/bin/activate
RUN pip install -r requirements-stg.txt
COPY . .
CMD ["fastapi", "run", "app/main.py" ]