FROM python:latest
COPY requirements-dev.txt requirements-dev.txt
RUN python3 -m venv .venv
RUN . .venv/bin/activate
RUN pip install -r requirements-dev.txt
COPY . .
CMD ["fastapi", "dev", "app/main.py" ]