name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [development, master]
  push:
    branches:
      - development
      - feature/**
    tags: 
      - '**'

jobs:
  determine-environment:
    uses: TokioFinal/tokio_reusable_workflows/.github/workflows/determine_environment.yaml@v2

  test:
    uses: TokioFinal/tokio_reusable_workflows/.github/workflows/test_python_app.yaml@v2

  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: 'fs'
          scan-ref: 'app/'
          format: 'table'
          exit-code: 1
          ignore-unfixed: false
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'
     
  build:
    needs: [ test, determine-environment ] 
    uses: ./.github/workflows/build_${{github.event.inputs.environment}}.yaml
    